import React, { Component } from "react";
import Stats from "./Stats";
import TwitterHeader from "./TwitterHeader";
import PersonTweets from "./PersonTweets";
class RightContainer extends Component {
  constructor() {
    super();
    this.state = {
      stats: [
        {
          id: "4",
          tweets: "3049",
          following: "344",
          followers: "434",
          likes: "455",
          moments: "34"
        }
      ],
      tweets: [
        {
          id: "23",
          Tweet1:
            "spite  generated by that tweet, SunnyD never  about what inspired the tweet,             aside from this vague message:"
        }
      ]
    };
  }
  render() {
    return (
      <div style={rigthContaineDimension}>
        <Stats statsfigure={this.state.stats} />
        <TwitterHeader />
        <PersonTweets personTweet={this.state.tweets} />
        <PersonTweets personTweet={this.state.tweets} />
      </div>
    );
  }
}

const rigthContaineDimension = {
  width: "80%",
  background: "skyblue",
  float: "right"
};
const statsCont = {
  width: "70%",
  height: "30px"
};
export default RightContainer;
